version: '2'

services:
	cassandra-node-1:
		image: cassandra_2.0.7_centos_6.6:latest
           	networks:
      			comm_net:
        			ipv4_address: 10.0.2.15
        cassandra-node-2:
                image: cassandra_2.0.7_centos_6.6:latest  
                networks:
                        comm_net:
                                ipv4_address: 10.0.2.16
        cassandra-node-3:
                image: cassandra_2.0.7_centos_6.6:latest  
                networks:
                        comm_net:
                                ipv4_address: 10.0.2.17
networks:
	comm_net:
    		driver: bridge
    	ipam:
      		driver: default
      		config:
      		- subnet: 10.0.2.0/24
        	gateway: 10.0.2.1
